# Generated by Django 4.2.7 on 2026-01-13 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('internship_domain', models.CharField(max_length=100)),
                ('internship_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offer_letter_file', models.FileField(upload_to='offer_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('noc_file', models.FileField(blank=True, null=True, upload_to='noc_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('faculty_remarks', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=20)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IT', 'Information Technology')], max_length=50)),
                ('year_of_study', models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipCompletion',
            fields=[
                ('completion_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_duration', models.IntegerField(help_text='Duration in days')),
                ('completion_certificate', models.FileField(upload_to='completion_certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('completion_status', models.BooleanField(default=False)),
                ('faculty_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('completion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='internship.internshipapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='internship.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='internship.userprofile'),
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('work_summary', models.TextField()),
                ('skills_learned', models.TextField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('faculty_feedback', models.TextField(blank=True, null=True)),
                ('log_status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('pending', 'Pending')], default='submitted', max_length=20)),
                ('missed_log_count', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='internship.internshipapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='internship.userprofile')),
            ],
            options={
                'unique_together': {('student', 'application', 'week_number')},
            },
        ),
    ]
