# Generated by Django 4.2.7 on 2026-01-15 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('IT', 'Information Technology'), ('ENGLISH', 'English Literature'), ('HISTORY', 'History'), ('PSYCHOLOGY', 'Psychology'), ('SOCIOLOGY', 'Sociology'), ('ECONOMICS', 'Economics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('MATHEMATICS', 'Mathematics'), ('ARTS', 'Visual Arts'), ('MUSIC', 'Music'), ('THEATRE', 'Theatre Arts')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProgressProof',
            fields=[
                ('proof_id', models.AutoField(primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('work_sample', 'Work Sample'), ('attendance', 'Attendance Proof'), ('project_milestone', 'Project Milestone'), ('task_completion', 'Task Completion'), ('presentation', 'Presentation/Demo'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proof_file', models.FileField(help_text='Upload proof: PDF, Image (JPG/PNG), or Video (MP4/AVI/MOV)', upload_to='progress_proofs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'doc', 'docx'])])),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('faculty_remarks', models.TextField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_proofs', to='internship.internshipapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_proofs', to='internship.userprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to='internship.userprofile')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
