# Generated by Django 4.2.7 on 2026-01-15 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_userprofile_department_progressproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='noc_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='noc_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='offer_letter_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='offer_letter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipcompletion',
            name='completion_certificate_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipcompletion',
            name='completion_certificate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='progressproof',
            name='proof_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressproof',
            name='proof_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='progressproof',
            name='proof_file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='internshipcompletion',
            name='completion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='completion_certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='progressproof',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Upload proof: PDF, Image (JPG/PNG), or Video (MP4/AVI/MOV)', null=True, upload_to='progress_proofs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'doc', 'docx'])]),
        ),
    ]
