# Generated by Django 4.2.7 on 2026-01-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_internshipapplication_noc_file_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='internship.userprofile'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='application_status',
            field=models.CharField(choices=[('pending_company', 'Pending - Awaiting Company Offer Letter'), ('pending_faculty', 'Pending - Faculty Review'), ('approved', 'Approved by Faculty'), ('rejected_company', 'Rejected - Company Issue'), ('rejected_faculty', 'Rejected by Faculty')], default='pending_faculty', max_length=30),
        ),
    ]
