# Generated by Django 4.2.7 on 2026-01-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_internshipapplication_assigned_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('BCOM_AF', 'B.Com Accounting & Finance'), ('BCOM_CA', 'B.Com CA'), ('BCOM_CS', 'B.Com CS'), ('BCOM', 'B.Com Commerce'), ('BCOM_IT', 'B.Com IT'), ('BCOM_IB', 'B.Com International Business'), ('BCOM_PA', 'B.Com Professional Accounting'), ('MCOM_CA', 'M.Com CA'), ('MCOM_IB', 'M.Com International Business'), ('CSE', 'B.Sc Computer Science'), ('BSC_AI', 'B.Sc AI & ML'), ('BSC_CS_COG', 'B.Sc CS with Cognitive Systems'), ('BSC_CS_CYB', 'B.Sc CS with Cyber Security'), ('BSC_CT', 'B.Sc Computer Technology'), ('BSC_DS', 'B.Sc Data Science & Analytics'), ('IT', 'B.Sc Information Technology'), ('BCA', 'BCA - Bachelor of Computer Applications'), ('BSC_BIO', 'B.Sc Biotechnology'), ('MSC_BIO', 'M.Sc Biotechnology'), ('BSC_MICRO', 'B.Sc Microbiology'), ('PHYSICS', 'B.Sc Physics'), ('MATHEMATICS', 'B.Sc Mathematics'), ('ECE', 'B.Sc Electronics and Communication Systems'), ('ENGLISH', 'BA English Literature'), ('BSC_ANIM', 'B.Sc Animation & Visual Effects'), ('BSC_VISCOM', 'B.Sc Visual Communication'), ('BSC_FASHION', 'B.Sc Costume Design & Fashion'), ('BBA', 'BBA'), ('BBA_CA', 'BBA CA'), ('BBA_LOG', 'BBA Logistics'), ('BSC_CATERING', 'B.Sc Catering Science & Hotel Management'), ('BSC_FOOD', 'B.Sc Food Processing Technology & Management')], max_length=50),
        ),
    ]
