# Generated by Django 4.2.7 on 2026-01-16 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklylog',
            options={'ordering': ['week_number']},
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description/comments', null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed by Faculty')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to='internship.userprofile'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Upload your weekly work proof (PDF, Image, Document, or Video)', null=True, upload_to='weekly_submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'mp4', 'avi', 'mov'])]),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='submission_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='submission_file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='log_status',
            field=models.CharField(blank=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='skills_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='work_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
